### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by isaacnass** [Coobaha/typed-fastify#25]
Hey I know this isn't quite an _issue_ but I just wanted to say "Thank you"! 

This is a pretty cool project and it really gives Fastify a first-class feeling when it comes to Typescript. With a little bit of funkiness I've been able to use this to share declaration files between backend and frontend, all thanks to you!

Keep developing, you're onto something. Expect a PR from me over the next few weeks for sure 👍

**Comment by Coobaha** [comment]
Hey, thanks for the feedback :) Please let me know if something is missing and I am looking forward for the first PR :D
