### ISSUE TITLE
Would it be possible to infer the params from the URL?

### ISSUE THREAD

**Issue by valerioleo** [Coobaha/typed-fastify#38]
Hey, thanks so much for this fantastic plugin! It's really helping in my project in keeping frontend and backend devs together.

I would love to take this even further and I have asked the following question on [SO](https://stackoverflow.com/questions/70109912/typescript-in-an-object-use-key-string-to-compute-its-value-type):

> I have found this fantastic fastify plugin (https://github.com/Coobaha/typed-fastify) that uses the following syntax to infer the correct types passed to the Service, given a schema of type T.
> ```javascript
> import {Schema, Service} from '@coobaha/typed-fastify';
> 
> 
> interface ExampleSchema extends Schema {
>   paths: {
>     'GET /test/:testId': {
>       request: {
>         params: {
>           testId: {
>             type: 'string',
>           }
>         };
>       };
>       // other properties, not relevant for question
>     };
>   };
> }
> 
> const exampleService: Service<ExampleSchema> = {
>   'GET /test/:testId': (req, reply) => {
>     const testId = req.params.testId // this passes ✅
>     const testName = req.params.testName // this fails 💔 
>  
>     // rest of handler
>   }
> };
> 
> // example is simplified. Find a full example here: https://github.com/Coobaha/typed-fastify
> ```
> This plugin is already awesome, but I want to take it even further.
> 
> Given a /test/:testId string, we already know which parameters that URL needs. Having to specify it twice (in the URL and the params object), it seems to me something worth trying to automate in order to guarantee they always stay in sync.
> 
> I would love to find a way to automatically add the params type, computing it from the key string (the endpoint URL). For example, the key /test/:testId should have a params of type {testId: string}.
> 
> Imagine doing:
> ```javascript
> import {Schema, Service} from '@coobaha/typed-fastify';
> 
> 
> interface ExampleSchema extends Schema {
>   paths: {
>     'GET /test/:testId': {
>        // only other properties, no need for explicit params
>     };
>   };
> }
> 
> // and still have the same type-checks on the params 🤯:
> const exampleService: Service<ExampleSchema> = {
>   'GET /test/:testId': (req, reply) => {
>     const testId = req.params.testId // this passes ✅
>     const testName = req.params.testName // this fails 💔 
>  
>     // rest of handler
>   }
> };
> ```
> In my understanding, this would be impossible with default typescript features and possibly only with a plugin to use at compile time using ttypescript.
> 
> Is there any way I can avoid using alternative compilers and writing my own plugins?
> 
> Thanks for any support

If I find a way, I would open a PR. I'm sure it will be handy :)

**Comment by Coobaha** [comment]
@valerioleo Hey, thanks for bringing this :) I will add this feature soon and sorry for the late response! I missed Github notification :/

**Comment by Coobaha** [comment]
@valerioleo https://github.com/Coobaha/typed-fastify/pull/41 here is PR that implements this feature,
- it prefers schema type if present, cause if schema params type is number it will be casted in runtime to number during validation.
- it also now catches typos in params, so it won't be possible to build invalid params validation based on schema due to typo.

**Comment by Coobaha** [comment]
Fixed and released as `v0.6.0`, please let me know if something is not working as expected :)
