### ISSUE TITLE
JSON type mismatch

### ISSUE THREAD

**Issue by qwelias** [Coobaha/typed-fastify#56]
As per standard `JSON.stringify` uses `toJSON` method on objects when possible to get JSON representation, unfortunately TS does not really have any built-ins to respect that behavior.

In `typed-fastify` it causes problems in cases where response type has any members with special `toJSON` implementation.
[`mongodb/ObjectId`](https://github.com/mongodb/js-bson/blob/main/src/objectid.ts#L202) as an example, so generated JSONSchema has these members as type `object` (because `ObjectId` is an object), but when `JSON.strigify`ed it becomes a string, so response validation in fastify fails.

I'm not sure what's the best approach here would be, but I have a suggestion:
- there are 3rd party solutions to base TS problem, such as [type-fest/Jsonify](https://github.com/sindresorhus/type-fest/blob/main/source/jsonify.d.ts#L81)
- when generating a schema the types passed into it should be `Jsonify`ed, so that jenerated JSONSchema accounts for any transformations (should probably be fixed in `typescript-json-schema`)
- should not affect `reply.status().send()`, but optionally it may make sense to allow it to take types compatible with `Jsonify`ed type

**Comment by Coobaha** [comment]
If I understood correctly you are dealing with

```
type MyData =  {
 _id: ObjectId
}
```

and generated schema output for `_id` is `object` in json schema? will using `@type` annotation solve this? https://github.com/YousefED/typescript-json-schema#annotations:

```
// input
/**
 @type string
*/
interface ObjectId extends String {
  toString(): string;
  toJSON(): string;
}
```

If this is exactly your issue - there is no way for https://github.com/YousefED/typescript-json-schema to figure out what to generate, so we should it hint it. 

@qwelias If this solves it - please close this issue 👍

**Comment by Coobaha** [comment]
Documented this in #59

**Comment by qwelias** [comment]
Unfortunately it seems to break TS validation [here](https://github.com/qwelias/typed-fastify-test)
```
src/schema.ts:2:15 - error TS2440: Import declaration conflicts with local declaration of 'ObjectId'.

2 import type { ObjectId } from 'mongodb'
                ~~~~~~~~

src/api.ts:13:5 - error TS2740: Type 'ObjectId' is missing the following properties from type 'ObjectId': charAt, charCodeAt, concat, indexOf, and 44 more.

13     _id: new ObjectId(),
       ~~~

  src/schema.ts:16:5
    16     _id: ObjectId
           ~~~
    The expected type comes from property '_id' which is declared here on type 'Document'


Found 2 errors.

```

**Comment by qwelias** [comment]
It kind of works if you remove `extends String`, let me see if there woud be other conflicts

**Comment by Coobaha** [comment]
I've used custom Objectid just for illustration purpose of implientation, it is not needed for schema generation to work

```typescript
interface ObjectId extends String {
  toString(): string;
  toJSON(): string;
}
```

what you should do probably in your schema is annotating mongodb objectid with`@typed` directly in schema or aliasing it with `@type` annotation

```typescript

import { ObjectId } from 'mongodb'
export type Document = {
    /**
     @type string
     */
    _id: ObjectId
}
// or

/**
@type string
*/ 
type myid = Objectid;

export type Document = {
    _id: myid
}
```

**Comment by qwelias** [comment]
> what you should do probably in your schema is annotating mongodb objectid with@type directly in schema or aliasing it with @type annotation

This could fix it for JSON schema generation, but in turn would break it for other parts of the code where `Document` is reused (e.g. comms with DB, where it expects actual `ObjectId`).

**Comment by qwelias** [comment]
I tried annotating it with `@TJS-type string`, but it doesn't seem to work

**Comment by qwelias** [comment]
I tried separating `Document` definition from `Schema` [here](https://github.com/qwelias/typed-fastify-test/blob/try-separate/src/schema.ts), but it just generates wonky JSON schema with two `ObjectId`s second referencing the original from Mongo, so annotation is ignored

**Comment by qwelias** [comment]
My gut feeling is it should be fixed on `typescript-json-schema`'s side, since it's supposed to return JSON-representation of TS type, yet it ignores `toJSON` method

**Comment by qwelias** [comment]
Will also look into using https://github.com/vega/ts-json-schema-generator, as type aliases like `AB` in my  example inlined with `typescript-json-schema`

**Comment by Coobaha** [comment]
Yes it `typescript-json-schema` issue, only workaround I see is type mapping things when sending request or calling `toString()` explicitly on ObjectID instance when sending response
